# Anchors
defaults: &defaults
  executor:
    name: node/default
    tag: 'lts'

version: 2.1
orbs:
  node: circleci/node@2.1
  aws-s3: circleci/aws-s3@1.1.1
jobs:
  build-and-publish:
    <<: *defaults
    steps:
      - checkout
      - run: echo "registry=$SYM_NPM_READ_REPO" > ~/.npmrc
      - run: echo "_auth=$SYM_NPM_TOKEN" >> ~/.npmrc
      - run: echo "always-auth=true" >> ~/.npmrc
      - run: echo "email=$SYM_NPM_EMAIL" >> ~/.npmrc
      - run: yarn
      - run: yarn build
      - run: bash ./publish.sh
      - run: rm -f ~/.npmrc
      - run: yarn build-storybook
      - persist_to_workspace:
          root: dist
          paths:
            - storybook
            - css
            - fonts

  deploy-storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/dist
      - aws-s3/sync:
          arguments: --delete
          from: /tmp/dist/storybook
          to: s3://uitoolkit-storybook/styles
  deploy-cdn:
    <<: *defaults
    parameters:
      cdn_version_path:
        type: string
        default: master
    steps:
      - run: touch test.txt
      - aws-s3/copy:
          aws-access-key-id: AWS_ACCESS_KEY_CDN
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_CDN
          aws-region: AWS_REGION_CDN
          from: ./test.txt
          to: s3://www-prod.symphony.com/resources/ui-toolkit/<< parameters.cdn_version_path >>/
      # - attach_workspace:
      #     at: /tmp/dist
      # - aws-s3/sync:
      #     arguments: '--delete --dryrun'
      #     aws-access-key-id: AWS_ACCESS_KEY_CDN
      #     aws-secret-access-key: AWS_SECRET_ACCESS_KEY_CDN
      #     aws-region: AWS_REGION_CDN
      #     from: /tmp/dist/fonts
      #     to: s3://www-prod.symphony.com/resources/ui-toolkit/<< parameters.cdn_version_path >>/fonts

workflows:
  build:
    jobs:
      - build-and-publish:
          filters:
            tags:
              only: /^v.*$/
      - deploy-storybook:
          requires:
            - build-and-publish
          filters:
            tags:
              only: /^v.*$/
            branches:
              ignore: /.*/
      - deploy-cdn:
          cdn_version_path: << pipeline.git.tag >>
          # requires:
          #   - build-and-publish
          # filters:
          #   branches:
          #     only: master
          #   tags:
          #     only: /^v.*\d$(?!^v.*SNAPSHOT$)/
